loss: {
    "class": "LossFunction",
    "train_enable_list": [
        rec_loss,
        rec_residual_loss,
        sky_color_loss,
        st_color_loss,
        st_alpha_loss,
    ],
    "debug_enable_list": [
        psnr,
        lpips,
        ssim,
    ],
    "train_loss": {
        "rec_loss": {"name": "rec_loss","args": ["pred", "scene_color"],  "mode": "l1", "scale": 1.0, "config": {"tonemap": gamma_log}},
        "rec_residual_loss": {"args": ["pred_scene_light_no_st", "scene_light_no_st"],  "mode": "l1", "scale": 1.0, "config": {"tonemap": gamma_log, "skybox_mask_out": true}},
        "sky_color_loss": {"args": ["pred_sky_color", "sky_color"], "mode": "charbonnier_l1", "config": {"tonemap": gamma_log, "skybox_mask": true}},
        "st_color_loss": {"args": ["pred_st_color", "st_color"], "mode": "charbonnier_l1", "scale": 1.0, "config": {"tonemap": gamma_log}},
        "st_alpha_loss": {"args": ["pred_st_alpha", "st_alpha"], "mode": "charbonnier_l1", "config": {}},
    },
    "debug_loss": {
        "psnr": {"args": ["pred", "scene_color"], "mode": "psnr", "config": {"tonemap": aces, "skybox_mask": false}},
        "ssim": {"args": ["pred", "scene_color"], "mode": "ssim", "config": {"tonemap": aces, "skybox_mask": false}},
        "lpips": {"args": ["pred","scene_color", ], "mode": "lpips", "config": {"tonemap": aces, "skybox_mask": false}},
        "psnr_no_st": {"args": ["pred_scene_color_no_st", "scene_color_no_st"], "mode": "psnr", "config": {"tonemap": aces, "skybox_mask": false}},
        "ssim_no_st": {"args": ["pred_scene_color_no_st", "scene_color_no_st"], "mode": "ssim", "config": {"tonemap": aces, "skybox_mask": false}},
        "lpips_no_st": {"args": ["pred_scene_color_no_st","scene_color_no_st", ], "mode": "lpips", "config": {"tonemap": aces, "skybox_mask": false}, 'enable': true},
        "psnr_st": {"args": ["pred_st_color", "st_color"], "mode": "psnr", "config": {"tonemap": aces, "skybox_mask": false}},
        "ssim_st": {"args": ["pred_st_color", "st_color"], "mode": "ssim", "config": {"tonemap": aces, "skybox_mask": false}},
        "lpips_st": {"args": ["pred_st_color","st_color", ], "mode": "lpips", "config": {"tonemap": aces, "skybox_mask": false}, 'enable': true},
    },
    "test_loss":{
        "psnr": {"args": ["pred", "scene_color"], "mode": "psnr", "config": {"tonemap": aces, "skybox_mask": false}},
        "lpips": {"args": ["pred","scene_color", ], "mode": "lpips", "config": {"tonemap": aces, "skybox_mask": false}},
        "ssim": {"args": ["pred", "scene_color"], "mode": "ssim", "config": {"tonemap": aces, "skybox_mask": false}},
    },
}
"log": {
    "train_scalar_epoch_sum": 5,
    "train_image_epoch_sum": 1,
    "train": {
        "he_0_prob": {"name": "p0", "fmt": "{:.2g}", "bar_step": false, "bar_epoch": true, "log_step": true, "log_epoch": true},
        "he_1_prob": {"name": "p1", "fmt": "{:.2g}", "bar_step": false, "bar_epoch": true, "log_step": true, "log_epoch": true},
        "he_2_prob": {"name": "p2", "fmt": "{:.2g}", "bar_step": false, "bar_epoch": true, "log_step": true, "log_epoch": true},
        "rendered_prob": {"name": "pr", "fmt": "{:.2g}", "bar_step": false, "bar_epoch": true, "log_step": true, "log_epoch": true},
        "lr": {"fmt": "{:.3e}", "bar_step": true, "log_step": true},
        "loss": {"fmt": "{:.3e}", "bar_step": true, "bar_epoch": true, "log_step": true, "log_epoch": true},
        "rec_loss": {"fmt": "{:.3e}", "bar_step": false, "bar_epoch": false, "log_step": true, "log_epoch": true},
        "rec_residual_loss": {"fmt": "{:.3e}", "bar_step": false, "bar_epoch": false, "log_step": true, "log_epoch": true},
        "residual_item_loss": {"fmt": "{:.3e}", "bar_step": false, "bar_epoch": false, "log_step": true, "log_epoch": true},
        "sky_color_loss": {"fmt": "{:.3e}", "bar_step": false, "bar_epoch": false, "log_step": true, "log_epoch": true},
        "st_color_loss": {"fmt": "{:.3e}", "bar_step": false, "bar_epoch": false, "log_step": true, "log_epoch": true},
        "st_alpha_loss": {"fmt": "{:.3e}", "bar_step": false, "bar_epoch": false, "log_step": true, "log_epoch": true},
        "zero_flow_loss": {"fmt": "{:.3e}", "bar_step": false, "bar_epoch": false, "log_step": true, "log_epoch": true},
        "zero_flow2_loss": {"fmt": "{:.3e}", "bar_step": false, "bar_epoch": false, "log_step": true, "log_epoch": true},
        "c1_flow_loss": {"fmt": "{:.3e}", "bar_step": false, "bar_epoch": false, "log_step": true, "log_epoch": true},
        "psnr": {"fmt": "{:.5g}", "bar_step": true, "bar_epoch": true, "text_epoch": true, "log_step": true, "log_epoch": true},
        "ssim": {"fmt": "{:.5g}", "bar_step": false, "bar_epoch": false, "text_epoch": true, "log_step": true, "log_epoch": true},
        "lpips": {"fmt": "{:.5g}", "bar_step": false, "bar_epoch": false, "text_epoch": true, "log_step": true, "log_epoch": true},
        "psnr_no_st": {"fmt": "{:.5g}", "bar_step": true, "bar_epoch": true, "text_epoch": true, "log_step": true, "log_epoch": true},
        "ssim_no_st": {"fmt": "{:.5g}", "bar_step": false, "bar_epoch": false, "text_epoch": true, "log_step": true, "log_epoch": true},
        "lpips_no_st": {"fmt": "{:.5g}", "bar_step": false, "bar_epoch": false, "text_epoch": true, "log_step": true, "log_epoch": true},
        "psnr_st": {"fmt": "{:.5g}", "bar_step": true, "bar_epoch": true, "text_epoch": true, "log_step": true, "log_epoch": true},
        "ssim_st": {"fmt": "{:.5g}", "bar_step": false, "bar_epoch": false, "text_epoch": true, "log_step": true, "log_epoch": true},
        "lpips_st": {"fmt": "{:.5g}", "bar_step": false, "bar_epoch": false, "text_epoch": true, "log_step": true, "log_epoch": true},
    },
    "test": {
        "psnr": {"fmt": "{:.5g}", "bar_step": true, "text_step": true, "bar_epoch": true, "text_epoch": true, "log_step": true, "log_epoch": true},
        "ssim": {"fmt": "{:.5g}", "bar_step": false, "text_step": true, "bar_epoch": false, "text_epoch": true, "log_step": true, "log_epoch": true},
        "lpips": {"fmt": "{:.5g}", "bar_step": false, "text_step": true, "bar_epoch": false, "text_epoch": true, "log_step": true, "log_epoch": true},
        "psnr_no_st": {"fmt": "{:.5g}", "bar_step": true, "bar_epoch": true, "text_epoch": true, "log_step": true, "log_epoch": true},
        "ssim_no_st": {"fmt": "{:.5g}", "bar_step": false, "bar_epoch": false, "text_epoch": true, "log_step": true, "log_epoch": true},
        "lpips_no_st": {"fmt": "{:.5g}", "bar_step": false, "bar_epoch": false, "text_epoch": true, "log_step": true, "log_epoch": true},
        "psnr_st": {"fmt": "{:.5g}", "bar_step": true, "text_step": true, "bar_epoch": true, "text_epoch": true, "log_step": true, "log_epoch": true},
        "ssim_st": {"fmt": "{:.5g}", "bar_step": false, "text_step": true, "bar_epoch": false, "text_epoch": true, "log_step": true, "log_epoch": true},
        "lpips_st": {"fmt": "{:.5g}", "bar_step": false, "text_step": true, "bar_epoch": false, "text_epoch": true, "log_step": true, "log_epoch": true},
    },
}